version: '3.8'

networks:
  swarm-sample:
    driver: bridge

services:
  service1:
    container_name: service1
    build:
      context: ./
      dockerfile: ./dev.Dockerfile
    networks:
      - swarm-sample
    volumes:
      - ./:/app
    environment:
      - PORT=80
    ports:
      - 5000:80
    command: yarn workspace service1 dev
  service2:
    container_name: service2
    build:
      context: ./
      dockerfile: ./dev.Dockerfile
    volumes:
      - ./:/app
    networks:
      - swarm-sample
    environment:
      PORT: 80
    command: yarn workspace service2 dev