version: '3.8'

networks:
  swarm-sample:
    driver: overlay

services:
  service1:
    image: service1
    networks:
      - swarm-sample
    environment:
      PORT: 80
    ports:
      - 5000:80
    deploy:
      replicas: 2
  service2:
    image: service2
    networks:
      - swarm-sample
    environment:
      PORT: 80
    deploy:
      replicas: 2